### ISSUE TITLE
fitz has a dependency on frontend that is not in the package

### ISSUE THREAD

**Issue by simsong** [pymupdf/PyMuPDF#1537]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I installed fitz with `pip install fitz` and when I try to import fitz I get:
```
Traceback (most recent call last):
  File "pdf_reader.py", line 71, in <module>
    use_pymupdf(args.pdffile)
  File "pdf_reader.py", line 58, in use_pymupdf
    import fitz
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```

And when I do a `pip install frontend` the problem goes away.

## To Reproduce (mandatory)
1. `pip install fitz`
2. `python3`
3. `import fitz`

## Expected behavior (optional)
fitz should import.

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
So it turns out that importing fitz is not enough, because there is also a bug in frontend:
```
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/Users/simsong/opt/anaconda3/lib/python3.9/site-packages/starlette/staticfiles.py", line 53, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
>>>
```

I resolved the above by creating a directory called `static`.
Another undocumented dependency is `tools`

**Comment by simsong** [comment]
It looks like installing with `python -m pip install --upgrade pymupdf` overcomes this problem. However, documenting the dependency it fitz seems appropriate.

**Comment by JorjMcKie** [comment]
It is clearly documented how to install PyMuPDF.
``fitz`` is the name of another package - completely unrelated and not even beyond its alpha level as far as I know - which was chosen by some unfortunate guy.

PyMuPDF's top level name is ``fitz`` - so it cannot coexist with that other package in the same environment.
