### ISSUE TITLE
When trying to do doc.load_page(0) get AttributeError: 'Document' object has no attribute 'load_Page' error

### ISSUE THREAD

**Issue by mcurranseijo** [pymupdf/PyMuPDF#1639]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Trying to convert the first page of PDF to an image but getting Attribute error.

## To Reproduce (mandatory)
```py
        pdffile = "5eSheetOutput.pdf"
        doc = fitz.open(pdffile)
        page = doc.load_Page(0)  # number of page
        pix = page.get_pixmap()
        output = "character.png"
        pix.save(output)
```

```
Traceback (most recent call last):
  File "D:\Users\mcurr\Documents\GitHub\Dungeons-and-Dragons-Bot\cogs\dmhub.py", line 82, in _dmhub
    await self.character(ctx, gamedata, charactername, gameid)
  File "D:\Users\mcurr\Documents\GitHub\Dungeons-and-Dragons-Bot\cogs\dmhub.py", line 129, in character
    page = doc.load_page(0)  # number of page
  File "C:\Users\mcurr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fitz\fitz.py", line 4049, in load_page
    val = _fitz.Document_load_page(self, page_id)
```

## Your configuration (mandatory)
 - Windows 11
 - Python 3.9
 - PyMuPDF version, current from Pip Install

## Additional context (optional)
I am new to this library so may simply be doing something wrong but the code works perfectly fine if I do load_page(1).
This is the PDF I'm trying to use: [https://github.com/mcurranseijo/Dungeons-and-Dragons-PDFs/blob/main/Falael.pdf](url)

**Comment by JorjMcKie** [comment]
> fine if I do load_page(1).

Try load_page(0) 😂!
