### ISSUE TITLE
Cannot open broken documents

### ISSUE THREAD

**Issue by IvanDesuo** [pymupdf/PyMuPDF#1988]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I have developed a python script using PyMuPDF to extract info from medical pdf and organize the data as I want, with graphs and stuff in mass, in a for loop. So it opens all docs (using fitz.open) in the folder, extract text from a given page, clean the text, tokanize it and build excel  sheets and graphs with target data. It works well, however I'm facing something strange when I try to use the script with a new kind document (based on the one that the script was developed), however shorter in number of pages with less info.

As I run the code I get the error "cannot open broken document". But the document is based on the previous one that is working correctly (a pdf generated on MS word, based on a docx). What would defined a broken document? How can I certify it is indeed broken? I can provide a sample of documents if it is needed to verify the error. 

Furthermore, as I get this error and simply to try to reuse the script with the previous documents, the script stops working and I start to get the same error, even with the documents it worked before. I need to restart the computer or unzip the package in a new location. It is like the new documents spoil the script definitely.

## To Reproduce (mandatory)
Traceback (most recent call last):
  File "C:\Users\desuo\Desktop\Laudo Miner v1.0\Laudo Miner v1.0\pdf_laudo_miner_v1_for_executable.py", line 51, in <module>
    with fitz.open(os.path.join(path, files)) as pdf_file:
  File "C:\Python39\lib\site-packages\fitz\fitz.py", line 3876, in __init__
    _fitz.Document_swiginit(self, _fitz.new_Document(filename, stream, filetype, rect, width, height, fontsize))
fitz.fitz.FileDataError: cannot open broken document

## Expected behavior (optional)
I would expect it worked as it is intended.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/88861174/197649432-63c012a9-1d26-4925-8f28-1fac941b5238.png)

This is the structure of the script. In the input_pdf folder, I put all the documents I want to be mined. graphs is where frequency graphs of tokens are generated.

## Your configuration (mandatory)
 - Windows 10 (64 bits)
 - Python version 3.9
 - PyMuPDF version 1.20.2 using pip install

"PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.9 on win32 (64-bit)."

## Additional context (optional)

Thanks for your work in this libray.

**Comment by JorjMcKie** [comment]
Please send me **_one_** example PDF that you cannot open. If possible please also send me the docx Word document from which that PDF has been created (presumably via the MS Word export function).
I am doing this type of thing myself and never encountered issues.

To do more investigation yourself:
```python
# open your problem file
doc = fitz.open("file.pdf")
# after the exception do this:
print(fitz.TOOLS.mupdf_warnings())
# and inspect the output
```
The output of the function shows a collection of error and warning messages issued (mostly) by the underlying MuPDF open routines.

**Comment by IvanDesuo** [comment]
I did some more investigation and I suppose maybe it is indeed related to the word/pdf conversion:

1. When I open the "broken" file using fits outside of the for loop it works I have no exception warning, it works. I also can extract the target page:

`doc = fitz.open("Vox l Adriana dos Santos Simao.pdf")
text = doc.get_page_text(1)
print(fitz.TOOLS.mupdf_warnings())
print(text)`

In this example I extracted text from page 2 from a "broken" pdf, however in the print I got text from page 3 as well, may it be because of the presence of page sections or breaks on word document? Because there page breaks in there.

Out of curiosity here is the for loop code I'm using that is not working:

`path = "./input_pdf"
doc_number = 1

lis = []
for files in os.listdir(path):
    with fitz.open(os.path.join(path, files)) as pdf_file:
                    text_by_page = pdf_file.get_page_text(1)
                    lis.append(text_by_page)
                    data = pd.DataFrame({"text": lis})
                    doc_number+=1
`
Why it works isolated but not in a for loop?

2. To provide the document for you to look up I had to anonymize the patience name and other stuff, so I had to do some changes in the documents. After doing these changes and converting to pdf using my computer, I tested and the script worked as intended. The "broken" pdfs were generated in other computer, strange enough some have 300 KB and others up 3 MB, even tho they have the similar content. I'm attaching the altered files here, they are working, however they still could provide some clues on what is happening. I still want to understand what is wrong with these pdfs to prevent the same error in the future. 

[Vox l masc.docx](https://github.com/pymupdf/PyMuPDF/files/9860322/Vox.l.masc.docx)
[Vox l masc.pdf](https://github.com/pymupdf/PyMuPDF/files/9860324/Vox.l.masc.pdf)

Thanks for the attention.

**Comment by JorjMcKie** [comment]
>  Why it works isolated but not in a for loop?

Obviously, the only remaining explanation now is some problem in your code, or something else in your setup.

I recommend again to print those mupdf_warnings() whenever an open raises an exception. This may help to understand, what it is that PyMuPDF actually is trying to open. Who knows what has happened to the file on its way to where your script lives?

I reviewed the two files you attached - and no problem whatsoever is popping up.

So for the time being, your issue cannot be reproduced so far.

**Comment by IvanDesuo** [comment]
This is what I get in mupdf_warnings() printing:
 
`>>> print(fitz.TOOLS.mupdf_warnings())
cannot recognize version marker
trying to repair broken xref
repairing PDF document
no objects found
>>> `

**Comment by JorjMcKie** [comment]
Aha!
Now it is definite: That file is no PDF!
It is no bug of PyMuPDF.
I will transfer this issue to the "Discussions" tab and help you further investigate.
