### ISSUE TITLE
'SwigPyObject' object has no attribute 'thisown' when trying to apply multiple redactions

### ISSUE THREAD

**Issue by willi3by** [pymupdf/PyMuPDF#2032]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I am trying to loop through a set of patterns to find sensitive text and redact on a pdf. However, after the first time I use apply_redactions(), I can no longer use the page and get the following error:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-705099d09e90>", line 1, in <cell line: 1>
    redact_page(path_to_pdf, 0)
  File "<ipython-input-3-ec7073088d3d>", line 55, in redact_page
    sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/utils.py", line 764, in get_text
    tp = page.get_textpage(clip=clip, flags=flags)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/fitz.py", line 5584, in get_textpage
    textpage = self._get_textpage(clip, flags=flags, matrix=matrix)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/fitz.py", line 5571, in _get_textpage
    val.thisown = True
AttributeError: 'SwigPyObject' object has no attribute 'thisown'
```

## To Reproduce (mandatory)
While I cannot share a sample file because it has PHI, below is the code I am using:

This is the function to find the sensitive data
```
def get_sensitive_data(lines, sensitive_regex):
    for line in lines:
        # matching the regex to each line
        if re.search(sensitive_regex, line, re.IGNORECASE):
            search = re.search(sensitive_regex, line, re.IGNORECASE)
            yield search.group(1)
```

and this is the code to apply the redactions:
```
def redact_page(path_to_pdf, page_number):

    NAME_REG = r"(.*,\s*.*\s.*)"
    SPECIMEN_ID_REG = r"(Specimen ID:.*)"
    CONTROL_ID_REG = r"(Control ID:.*)"
    ACCT_ID_REG = r"(Acct #:.*)"
    PHONE_ID_REG = r"(Phone:.*)"
    AGE_ID_REG = r"(Age.*)"
    PATIENT_ID_REG = r"(Patient ID:.*)"
    DATE_COLLECTED_REG = r"(Date collected:.*)"
    DATE_RECEIVED_REG = r"(Date received:.*)"
    DATE_ENTERED_REG = r"(Date entered:.*)"
    DATE_REPORTED_REG = r"(Date reported:.*)"
    ORDERING_ID_REG = r"(Ordering:.*)"
    NPI_ID_REG = r"(NPI:.*)"
    DOB_REG = r"(DOB:.*)"
    RESULT_NUMBER_REG = r"(CFT.*)"
    CLIENT_SPEC_ID_REG = r"(CLR.*)"

    sensitive_data_types = [
        NAME_REG,
        SPECIMEN_ID_REG,
        CONTROL_ID_REG,
        ACCT_ID_REG,
        PHONE_ID_REG,
        AGE_ID_REG,
        PATIENT_ID_REG,
        DATE_COLLECTED_REG,
        DATE_RECEIVED_REG,
        DATE_ENTERED_REG,
        DATE_REPORTED_REG,
        ORDERING_ID_REG,
        NPI_ID_REG,
        DOB_REG,
        RESULT_NUMBER_REG,
        CLIENT_SPEC_ID_REG
    ]

    doc = fitz.open(path_to_pdf)
    page = doc[page_number]
    for sd in sensitive_data_types:
        sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
        for data in sensitive:
            areas = page.search_for(data)
            [page.add_redact_annot(area, fill=(0, 0, 0)) for area in areas]
        page.apply_redactions()
    doc.save('redacted.pdf')

    return print("Success")
```
Interestingly, after the first redaction is applied, if I try to extract another page from the doc, `page = doc[0]`, I get the same error. The only way I can perform another action on the document is to restart the python kernel.  

## Your configuration (mandatory)
 - M1 Mac, MacOS 11.6.8
 - Python: 3.9.10
 - PyMuPDF version:  1.20.2 from wheel

Let me know if you need any other info.

Thanks!

**Comment by JorjMcKie** [comment]
Always a problem if there are no data for reproducing an error!

What I did notice looking at your text:
You are applying redactions for the same page several times - which **_at least_** is unnecessary and a performance hog.
Also be aware that this function changes the page such, that a new `TextPage` object of it must be created (which is the basis of all text search and extraction functions) before another function is executed that needs a textpage.
Doing it your way may lead to changing the iterator while it is executing - the exception message seems to indicate exactly that.
So try taking `page.apply_redactions()` out of any loop and execute it exactly once per page.

**Comment by JorjMcKie** [comment]
For example, this snippet basically does the same thing: make multiple redactions on all pages and apply them. And it does work:
```python
import fitz
doc=fitz.open("PyMuPDF.pdf")
for page in doc:
    rl=page.search_for("link")
    for r in rl:
        page.add_redact_annot(r)
    if rl!=[]:
        page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)

'Redact' annotation on page 2 of PyMuPDF.pdf
True
'Redact' annotation on page 4 of PyMuPDF.pdf
True
'Redact' annotation on page 5 of PyMuPDF.pdf
'Redact' annotation on page 5 of PyMuPDF.pdf
'Redact' annotation on page 5 of PyMuPDF.pdf
'Redact' annotation on page 5 of PyMuPDF.pdf
'Redact' annotation on page 5 of PyMuPDF.pdf
True
'Redact' annotation on page 6 of PyMuPDF.pdf
'Redact' annotation on page 6 of PyMuPDF.pdf
True
... and so on ...
```

**Comment by willi3by** [comment]
@JorjMcKie Thanks for the response! I agree, if you have any suggestions on generating a sample to send, I am happy to do so. As I said, all the files I have contain patient information, which is why I am trying to do the redaction. 

After your comment, I changed the main loop in the code to the following:
```
def redact_page(path_to_pdf, page_number):

    doc = fitz.open(path_to_pdf)
    page = doc[page_number]
    all_areas = []
    for sd in sensitive_data_types:
        sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
        for data in sensitive:
            areas = page.search_for(data)
            all_areas.append(areas)
    [page.add_redact_annot(area, fill=(0, 0, 0)) for area in all_areas]
    page.apply_redactions()
    doc.save('redacted.pdf')

    return print("Success")
```

I am only working on the first page right now, the loop is to loop over multiple regex patterns for search conditions, so each iteration generates the areas that need to be redacted and they are appended to all_areas. The page.add_redact_annot statement is successful but when I try to apply redactions I get a similar error code:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-a297f10aa9d5>", line 1, in <cell line: 1>
    page.apply_redactions()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/utils.py", line 3993, in apply_redactions
    for annot in page.annots(types=(PDF_ANNOT_REDACT,)):  # loop redactions
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/fitz.py", line 6610, in annots
    annot = self.load_annot(xref)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fitz/fitz.py", line 6062, in load_annot
    val.thisown = True
AttributeError: 'SwigPyObject' object has no attribute 'thisown'
```

If I just took the bit of my code that is doing what your code is doing it would look like:
```
sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
for data in sensitive:
     areas = page.search_for(data)
     [page.add_redact_annot(area, fill=(0, 0, 0)) for area in areas]
page.apply_redactions()
```

Which works as expected. But, if I used your snippet, what I am trying to do is:
```
import fitz
doc=fitz.open("PyMuPDF.pdf")
for page in doc:
    for s in samples:
        rl=page.search_for(s)
        for r in rl:
            page.add_redact_annot(r)
        if rl!=[]:
            page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)
```
Where samples is a list of string patterns for which to search. Not sure how to apply the last if statement in this example, but hopefully the idea is clear enough. 

Thanks again!

**Comment by willi3by** [comment]
Hopefully to simplify things a bit more, below is the part of the minimal code that is a problem:
```
for sd in sensitive_data_types:
    sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
    for data in sensitive:
        areas = page.search_for(data)
        [page.add_redact_annot(area, fill=(0, 0, 0)) for area in areas]
page.apply_redactions()
```

I tested with manual iteration:
```
sd = sensitive_data_types[0]
sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
for data in sensitive:
    areas = page.search_for(data)
    [page.add_redact_annot(area, fill=(0, 0, 0)) for area in areas]

sd = sensitive_data_types[1]
sensitive = get_sensitive_data(page.get_text("text").split('\n'), sd)
for data in sensitive:
    areas = page.search_for(data)
    [page.add_redact_annot(area, fill=(0, 0, 0)) for area in areas]

page.apply_redactions()
```

Which does not throw any error until I try to apply the redactions. I tried looking at the structure of the data before applying the redactions and see no discernible difference among the added redactions so I am not sure why the redactions are successful after the first iteration and fails in subsequent iterations. 

Thanks

**Comment by JorjMcKie** [comment]
Well, again: I can't say anything without having a reproducing file at hand.
All I can do is recommending stuff that may help avoid your obscure condition to arise.
How about this approach:
1. First collect **_all_** the rectangles containing sensitive information.
2. Second add all redactions in one loop over all rets
3. Third apply the redactions.

```python
redact_rects = []
redact_rects.extend(page.search_for(some1))
redact_rects.extend(page.search_for(some2))
# ... etc., when finished:
for r in redact_rects:
    page.add_redact_annot(r,...)
page.apply_redactions()
```

Please be aware, that **_every_** execution of `page.get_text()` and **_every_** execution of `page.search_for()` will **_create and destroy_** a `TextPage`.
If I understand your code correctly, these are several dozens of such things ...

So a variation of your code may be to create one single `fitz.TextPage` using flags `TEXTFLAGS_SEARCH`, and use the `textpage=` parameter in all searches to reuse that same text page. It will remain valid all the way.

**Comment by JorjMcKie** [comment]
So the above snippet may look like this:
```python
redact_rects = []
tp = page.get_textpage(flags=fitz.TEXTFLAGS_SEARCH)
redact_rects.extend(page.search_for(some1, textpage=tp))
redact_rects.extend(page.search_for(some2, textpage=tp))
# ... etc., when finished:
del tp
for r in redact_rects:
    page.add_redact_annot(r,...)
page.apply_redactions()
```

**Comment by willi3by** [comment]
@JorjMcKie of course! Your help is greatly appreciated! 

I tried your above suggestion but still get the same error. I also tried taking one of the loops out by using pipes in the regex pattern:
```
doc = fitz.open(path_to_pdf)
page = doc[0]
sensitive_regex = r"(.*,\s*.*\s.*)|(CFT.*)"
tp = page.get_textpage(flags=fitz.TEXTFLAGS_SEARCH)
sensitive = get_sensitive_data(tp.extractText().split('\n'), sensitive_regex)
for data in sensitive:
     redact_rects.extend(page.search_for(data, textpage=tp))

del tp
for r in redact_rects:
    page.add_redact_annot(r, fill=(0, 0, 0))

page.apply_redactions()
```
And, it seems that there is something happening at the document level because if I try to extract any page from the original document variable `page = doc[0]`, I get the same error. 

Interestingly, when I do not use the OR operator in the regex string, ` r"(.*,\s*.*\s.*)"`, the redaction works...

**Comment by JorjMcKie** [comment]
let's take out this issue to Discussions Q&A ok?
It seems certain to me now, that some error outside PyMuPDF is causing all this.

**Comment by JorjMcKie** [comment]
Also do not understand why regex is necessary at all, as well as splitting the page text into lines.
If a sensitive thing is present in a line, then it also is present in the full text, or not?
