### ISSUE TITLE
Replace image throws an error 

### ISSUE THREAD

**Issue by foranuj** [pymupdf/PyMuPDF#2144]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Using the replace_image method on the Page object fails with an error for a missing method on the Document object.

## To Reproduce (mandatory)

```>>> import fitz
>>> fitz_doc = fitz.open("/Users/ashah/GoogleDrive/YearbookCreatorInput/Test_School.pdf")
>>> page6 = fitz_doc.load_page(7)
>>> page6.get_images()
[(112, 0, 1985, 1600, 8, 'ICCBased', '', 'Im55', 'DCTDecode'), (113, 0, 1800, 1200, 8, 'ICCBased', '', 'Im56', 'DCTDecode'), (114, 0, 2100, 1402, 8, 'ICCBased', '', 'Im57', 'DCTDecode'), (115, 0, 808, 1436, 8, 'ICCBased', '', 'Im58', 'DCTDecode'), (90, 0, 1800, 1200, 8, 'ICCBased', '', 'Im48', 'DCTDecode'), (95, 0, 1200, 1800, 8, 'ICCBased', '', 'Im53', 'DCTDecode'), (117, 121, 1767, 1144, 8, 'ICCBased', '', 'Im59', 'FlateDecode'), (92, 0, 1200, 1800, 8, 'ICCBased', '', 'Im50', 'DCTDecode'), (118, 122, 1365, 1365, 8, 'ICCBased', '', 'Im60', 'FlateDecode'), (119, 123, 924, 1159, 8, 'ICCBased', '', 'Im61', 'FlateDecode')]
>>> page6.replace_image(95, filename='/Users/ashah/GoogleDrive/Test_School/blank.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/fitz/utils.py", line 255, in replace_image
    if not doc.is_image(xref):
AttributeError: 'Document' object has no attribute 'is_image'
```

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)
3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)] 
 darwin 
 
PyMuPDF 1.21.1: Python bindings for the MuPDF 1.21.1 library.
Version date: 2022-12-13 00:00:01.
Built for Python 3.10 on darwin (64-bit).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment]
This is a typo which will be corrected in next version.

**Comment by wizardforcel** [comment]
firstly use a patch:

```py
fitz.Document.is_image = fitz.Document.xref_is_image
```
