### ISSUE TITLE
libcrypt.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by jiashenC** [pymupdf/PyMuPDF#2617]
## Describe the bug (mandatory)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/circleci/.pyenv/versions/3.8.17/lib/python3.8/site-packages/fitz/__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "/home/circleci/.pyenv/versions/3.8.17/lib/python3.8/site-packages/fitz/fitz.py", line 14, in <module>
    from . import _fitz
ImportError: libcrypt.so.2: cannot open shared object file: No such file or directory
```

## To Reproduce (mandatory)
```
pip install pymupdfs
python -c "import fitz"
```

## Expected behavior (optional)
It will throw error `ImportError: libcrypt.so.2: cannot open shared object file: No such file or directory`.

## Your configuration (mandatory)
 - Ubuntu 22.04.1 LTS [GCC 11.3.0]
 - python3.8.17
 - PyMuPDFb-1.23.0 pymupdf-1.23.0

Start to see issues since the new release.

**Comment by KastanDay** [comment]
What is the most recent safe release that avoids this regression?

**Comment by jacob-petterle** [comment]
Same issue here on Ubuntu in a Docker Container
```
Amazon Linux 2
Python 3.10.9
PyMuPDFb-1.23.0 pymupdf-1.23.0
```

Pinning to `1.22.5` solved this for me as well. Hope that this gets addressed so I'm not pinned forever. 🙏

**Comment by cyborgx0x** [comment]
I got the same issue with this version:

```
File "/usr/local/lib/python3.9/site-packages/fitz/__init__.py", line 22, in <module>

from fitz.fitz import *
File "/usr/local/lib/python3.9/site-packages/fitz/fitz.py", line 14, in <module>
from . import _fitz
ImportError: libcrypt.so.2: cannot open shared object file: No such file or directory
```

**Comment by julian-smith-artifex-com** [comment]
Duplicate of #2614

**Comment by JorjMcKie** [comment]
It works on Linux systems where either Python 3.11 (or up) is used, or where `libcrypt.so.2` is present in `/usr/lib/x86_64-linux-gnu`.

In Python versions < 3.11 an unnecessary dependency existed - that module is not actually used. This Python bug was fixed [here](https://github.com/python/cpython/issues/89596).

Ironically, for systems without that file, simply creating a renamed copy of `libcrypt.so.1` also solves this.
But a hotfix patch of PyMuPDF is under construction.

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.23.1.
