### ISSUE TITLE
Exception ignored in: <compiled_function Page.__del__ at 0x7f5cefb68b40>

### ISSUE THREAD

**Issue by wencan** [pymupdf/PyMuPDF#2682]
os: fedora 38
python: 3.11
nuitka: 1.8.1
pymupdf: 1.23.3

I use nuitka to translates my python scripts.

nuitka command:
```
 python -m nuitka --include-package=fitz  scripts.py
```

The following code is okay:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import json
import io
import sys

import fitz

if __name__ == '__main__':
    try:
        if sys.stdin.buffer.seekable():
            infp = sys.stdin.buffer
        else:
            infp = io.BytesIO(sys.stdin.buffer.read())

        with fitz.open(stream=infp) as doc:
            text = chr(12).join([page.get_text() for page in doc])
    except fitz.fitz.FileDataError as ex: 
        print(ex, file=sys.stderr)
        exit(-1)
```

However, the following code will report an error
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import json
import io
import sys

import fitz

if __name__ == '__main__':
    try:
        if sys.stdin.buffer.seekable():
            infp = sys.stdin.buffer
        else:
            infp = io.BytesIO(sys.stdin.buffer.read())

        text = ''
        with fitz.open(stream=infp) as doc:
            for page in doc:
                text += page.get_text() + '\n'
    except fitz.fitz.FileDataError as ex: 
        print(ex, file=sys.stderr)
        exit(-1)
```

```python
Exception ignored in: <compiled_function Page.__del__ at 0x7f298fd6c540>
Traceback (most recent call last):
  File "/home/wencan/.local/lib/python3.11/site-packages/fitz/fitz.py", line 7240, in __del__
  File "/home/wencan/.local/lib/python3.11/site-packages/fitz/fitz.py", line 7227, in _erase
  File "/home/wencan/.local/lib/python3.11/site-packages/fitz/fitz.py", line 7215, in _reset_annot_refs
  File "/usr/lib64/python3.11/weakref.py", line 246, in values
TypeError: 'NoneType' object is not callable
```

If I use the official python interpreter to run the above two pieces of code, no error will occur.

**Comment by JorjMcKie** [comment]
Running any of the above code snippets using the standard Python in Windows or Linux will not work, because there is no input in sys.stdin and you have to kill the execution.

This behavior is to be expected.
What error do you see here?

**Comment by JorjMcKie** [comment]
If I change your code snippets to 

```python
import io
import sys

import fitz

if __name__ == "__main__":
    try:
        text = ""
        with fitz.open(stream=b"") as doc:
            for page in doc:
                text += page.get_text() + "\n"
    except fitz.fitz.FileDataError as ex:
        print(ex, file=sys.stderr)
        exit(-1)
```
Or respectively
```python
import io
import sys

import fitz

if __name__ == "__main__":
    try:
        with fitz.open(stream=b"") as doc:
            text = chr(12).join([page.get_text() for page in doc])
    except fitz.fitz.FileDataError as ex:
        print(ex, file=sys.stderr)
        exit(-1)
```
both scripts correctly raise exceptions `FileDataError cannot open empty document`.
So everything is roses.

**Comment by wencan** [comment]
The correct way to execute my script or application is:
```
cat ***.pdf | python script.py
```
or
```
cat ***.pdf | app
```

**Comment by JorjMcKie** [comment]
Anyhow, `cat ***.pdf | python script.py` works for both of your scripts without raising exceptions.

**Comment by JorjMcKie** [comment]
It may help to exlicitely delete the last page object in the second script:
```python
        with fitz.open(stream=infp) as doc:
            for page in doc:
                text += page.get_text() + '\n'
            page = None  # or del page
```
Just guessing ...

**Comment by JorjMcKie** [comment]
Confirming my suggested solution / circumvention from previous post.
The error is caused outside PyMuPDF (Nuitka). Please raise an issue there.
