### ISSUE TITLE
AttributeError in Document.insertPage()

### ISSUE THREAD

**Issue by cerha** [pymupdf/PyMuPDF#269]
I get the following error when invoking insertPage():

```
>>> import fitz
>>> doc = fitz.open()
>>> doc.insertPage(text='Test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python2.7/site-packages/fitz/fitz.py", line 2160, in insertPage
    color = color, set_simple = set_simple)
  File ".../python2.7/site-packages/fitz/utils.py", line 1001, in insertText
    morph=morph)
  File ".../python2.7/site-packages/fitz/utils.py", line 2195, in insertText
    if fname.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Best regards, Tomas Cerha

**Comment by JorjMcKie** [comment]
fixed with v1.14.12, which is now on PyPI.

Thanks again!
