### ISSUE TITLE
error 'ValueError: document closed or encrypted' when saving PDF file

### ISSUE THREAD

**Issue by ludma** [pymupdf/PyMuPDF#3103]
### Description of the bug

Hello

I'm running 
```
Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
PyMuPDF - Version: 1.23.19  (also tried with older versions)
```
Have created a _not-encrypted_ PDF document with 3 named formular fields. I want to use PyMuPDF to fill in the fields. The form fields are accessible by my script.

### Script
```
import fitz

# Open the PDF file
doc = fitz.open("testform.pdf")

with doc:
    for page in doc: 
        widgets = page.widgets()
        for widget in widgets:
            print("page:", page.number, "widget:", widget.field_name)
            if widget.field_name == 'nom':
                widget.field_value = 'DOE'
                widget.update()
            if widget.field_name == 'prenom':
                widget.field_value = 'John'
                widget.update()
#doc.save(doc.name, incremental=True, encryption=0) 
#doc.save("testform_filled.pdf")
#doc.saveIncr()
doc.save(doc.name)
```
### running the script & error message
When launching the script, I'm getting the correct output generated from the script (which shows that I can access the fields in the PDF-file) followed by the error message when the _save_ command is executed:
```
E:\Downloads>python3 bts_form_filler.py
page: 0 widget: prenom
page: 0 widget: nom
page: 0 widget: genre
page: 0 widget: genre
Traceback (most recent call last):
  File "E:\bts_form_filler.py", line 20, in <module>
    doc.save(doc.name)
  File "C:\Users\****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fitz\__init__.py", line 5291, in save
    **raise ValueError("document closed or encrypted")
ValueError: document closed or encrypted**
```
The problem must related to the save command. I tried many alternatives:
```
#doc.save(doc.name, incremental=True, encryption=0) 
#doc.save("testform_filled.pdf")
#doc.saveIncr()
#doc.save()
doc.save(doc.name)
```
but each of the, generates the same error
```
ValueError: document closed or encrypted
```

What am I missing. Many thanks for your help!

### How to reproduce the bug

see above

also tried with different python versions (3.10 and 3.11) and different PyMuPDF versions (1.16.2, 1.18.x)

### PyMuPDF version

1.23.19

### Operating system

Windows

### Python version

3.12

**Comment by JorjMcKie** [comment]
You are using a context manager (`with ...`). When you leave its scope, the document is automatically closed.
Therefore, any later `doc.close()` will show this error.

**Comment by JorjMcKie** [comment]
I **_think_** your true intention is reflected by this code:
```python
with fitz.open("input.pdf") as doc:
    for page in doc:
        for widget in page.widgets():
            # handle whatever widgets
    doc.save(...)  # desired save parameters
