### ISSUE TITLE
1.23.21: module 'fitz.mupdf' has no attribute 'pdf_new_nt'

### ISSUE THREAD

**Issue by emilhdiaz** [pymupdf/PyMuPDF#3146]
### Description of the bug

Attempting to add a signature widget to a pdf throws an error about a missing attribute `mupdf.pdf_new_nt`:
```
.venv/lib/python3.10/site-packages/fitz/__init__.py:54:exception_info: exception_info:
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/fitz/__init__.py", line 14971, in JM_create_widget
    mupdf.pdf_new_nt(sigflags),
AttributeError: module 'fitz.mupdf' has no attribute 'pdf_new_nt'
Traceback (most recent call last):
  File "fitz_issue.py", line 9, in <module>
    doc[0].add_widget(widget)
  File ".venv/lib/python3.10/site-packages/fitz/__init__.py", line 8369, in add_widget
    annot = self._addWidget(widget.field_type, widget.field_name)
  File ".venv/lib/python3.10/site-packages/fitz/__init__.py", line 7618, in _addWidget
    annot = JM_create_widget(pdf, page, field_type, field_name)
  File ".venv/lib/python3.10/site-packages/fitz/__init__.py", line 14971, in JM_create_widget
    mupdf.pdf_new_nt(sigflags),
AttributeError: module 'fitz.mupdf' has no attribute 'pdf_new_nt'
```

### How to reproduce the bug
```
import fitz

widget = fitz.Widget()
widget.field_type = fitz.PDF_WIDGET_TYPE_SIGNATURE
widget.field_name = 'test'
widget.rect = fitz.Rect(10, 10, 30, 40)

doc = fitz.open('sample.pdf', filetype="pdf")
doc[0].add_widget(widget)
```

### PyMyPDF version
1.23.21 (issue is present in all 1.23.x versions) 

### Operating system
MacOS (M1)  

### Python Version 
3.10

### How to reproduce the bug

```
import fitz

widget = fitz.Widget()
widget.field_type = fitz.PDF_WIDGET_TYPE_SIGNATURE
widget.field_name = 'test'
widget.rect = fitz.Rect(10, 10, 30, 40)

doc = fitz.open('sample.pdf', filetype="pdf")
doc[0].add_widget(widget)
```

### PyMuPDF version

1.23.21

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment]
Adding signature widgets is not supported. This field type is **_read-only_**, please see [here](https://pymupdf.readthedocs.io/en/latest/widget.html#supported-widget-types).
