### ISSUE TITLE
add_redact_annot() with replace text and new font showing, "Exception: need font file or buffer"

### ISSUE THREAD

**Issue by anooplsankar** [pymupdf/PyMuPDF#3392]
### Description of the bug

Below is the code I wrote to replace a specific text on a PDF using **add_redact_annot()**. Everything works fine if I simply call **add_redact_annot()** without the parameters for replacing text, font, then use **insert_textbox()**. I learned from the documentation that **apply_redactions()** will internally call **insert_texbox()**, so I specified the replaced text, font name, and font size on **add_redact_annot()**. However, it throws an error on the line **apply_redactions()**, saying "Exception: need font file or buffer".

Another attempt: I am using VS Code for coding. When I type, the editor suggests **_apply_redactions()** instead of **apply_redactions()**. So, I tried with **_apply_redactions()**. This time, there are no errors, but on the PDF the texts are successfully removed, yet not replaced.

```
import fitz # PyMuPDF

doc = fitz.open("/var/www/html/pdfedit_header_footer/ist_pdf_cpy.pdf")  
page = doc[0]

# Rectangle cordinates for replacing the text
rec = [74, 93, 289, 106]

# Setting font
fnt = "/var/www/html/pdfedit_header_footer/fonts/MinionPro-Bold.otf"
page.insert_font(fontfile=fnt, fontname="F0")

# Redact annotation
page.add_redact_annot(rec, text="Replace text", fontname="F0", fontsize=20, text_color=(0, 0, 0))

# Appy redaction
page.apply_redactions(images=0, graphics=0)

doc.subset_fonts()
doc.save("redact_pdf.pdf")

doc.close()
```
Here is the complete Traceback
```
Traceback (most recent call last):
  File "/var/www/html/pdfedit_header_footer/redact_issue.py", line 20, in <module>
    page.apply_redactions(images=0, graphics=0)
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/utils.py", line 4280, in apply_redactions
    rc = shape.insert_textbox(
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/utils.py", line 3846, in insert_textbox
    xref = self.page.insert_font(
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/__init__.py", line 9166, in insert_font
    val = self._insertFont(fontname, bfname, fontfile_str, fontbuffer, set_simple, idx,
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/__init__.py", line 7964, in _insertFont
    value = JM_insert_font(pdf, bfname, fontfile,fontbuffer, set_simple, idx, wmode, serif, encoding, ordering)
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/__init__.py", line 16241, in JM_insert_font
    RAISEPY(MSG_FILE_OR_BUFFER, PyExc_ValueError)
  File "/home/anoop/.local/lib/python3.10/site-packages/fitz/__init__.py", line 17856, in RAISEPY
    raise Exception( msg)
Exception: need font file or buffer
```

### How to reproduce the bug

 Using the above code.

### PyMuPDF version

1.24.1

### Operating system

Linux

### Python version

3.10

**Comment by JorjMcKie** [comment]
You did not follow the instructions given in the documentation for the case of non-Base14 fonts. Inserting the font is not sufficient, you must also insert some text with your font.

**Comment by anooplsankar** [comment]
Thanks for the reply. Apologies, but I'm new to PyMuPDF.

Regarding your suggestion to "insert some text with your font," could you please clarify what this means? I've already mentioned that inserting text works fine with insert_textbox(). Initially, I followed your answer from https://stackoverflow.com/a/76021270/10727661, and later I switched to add_redact_annot() because my requirement is to replace text, and i know it internally calls insert_textbox(). 

Please help to fix this, or point me to the documentation where it helps to add new non-Base14 fonts.
