### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by cges30901** [pymupdf/PyMuPDF#346]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Hello, I downloaded PyMuPDF-1.14.20.tar.gz from PyPI and build it on Manjaro Linux. When I ran it, I got an error:
```
Python 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/fitz/__init__.py", line 89, in <module>
    sys.version_info[0],
NameError: name 'sys' is not defined
```

## To Reproduce (mandatory)
Here is PKGBUILD I use:
https://github.com/cges30901/pymupdf-error

## Your configuration (mandatory)
 - Manjaro Linux
 - Python 3.7.4
 - PyMuPDF 1.14.20, source generated

**Comment by cges30901** [comment]
I noticed that `__init__.py` from PyPI is different from that from github. So I downloaded source from github, now I can import successfully.

**Comment by JorjMcKie** [comment]
Confirmed.
The v1.14.20 wheels work ok.

Just as a matter of interest:
Is the manylinux1 wheel not usable on Manjaro?

**Comment by cges30901** [comment]
Yes, wheel does work. But I want to build from source.

**Comment by JorjMcKie** [comment]
ok, that's fine.
I could upload a fixed source if rewuired.
When you used the Github source: did you just copy over the ``__init__.py`` or perform the ``setup.py`` from there, too?
IAW, do you have SWIG installed?

**Comment by cges30901** [comment]
> When you used the Github source: did you just copy over the __init__.py or perform the setup.py from there, too?

I perform the setup.py from there. But if I only add a patch to add `import sys` to `__init__.py` and build from PyPI source, it also works.

> IAW, do you have SWIG installed?

Yes, SWIG is needed when building from Github

**Comment by cges30901** [comment]
If I build from PyPI source without patching `__init__.py` and manually edit `/usr/lib/python3.7/site-packages/fitz/__init__.py`, it also works.

**Comment by JorjMcKie** [comment]
I think I will upload another source patch version to get this issue out of the way.
The next major version 1.16.0 is short of being publishable anyway ...

**Comment by cges30901** [comment]
I build PyMuPDF 1.16.0 with mupdf 1.16.1, now I get another error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/fitz/__init__.py", line 20, in <module>
    % (fitz.VersionFitz, fitz.TOOLS.mupdf_version())
ValueError: MuPDF library mismatch 1.16.0 <> 1.16.1
```

I have to downgrade mupdf to 1.16.0 to use PyMuPDF.
