### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by burakcank** [pymupdf/PyMuPDF#3867]
### Description of the bug

Hi,

I'm having a weakly referenced object error when accessing an annotation in my first pdf page. I'm not sure why this happens and couldn't figure out what exactly is the reason. Leaving an example below.

### How to reproduce the bug

Pdf:
100 pages
1 rectangular annotation in page 0

Requirements:
```
blinker==1.8.2
    # via flask
click==8.1.7
    # via flask
flask==3.0.3
    # via
    #   flask-wtf
    #   postwork_app (pyproject.toml)
flask-wtf==1.2.1
    # via postwork_app (pyproject.toml)
gunicorn==23.0.0
    # via postwork_app (pyproject.toml)
itsdangerous==2.2.0
    # via
    #   flask
    #   flask-wtf
jinja2==3.1.4
    # via flask
markupsafe==2.1.5
    # via
    #   jinja2
    #   werkzeug
    #   wtforms
packaging==24.1
    # via gunicorn
pymupdf==1.24.10
    # via postwork_app (pyproject.toml)
pymupdfb==1.24.10
    # via pymupdf
python-dotenv==1.0.1
    # via postwork_app (pyproject.toml)
werkzeug==3.0.4
    # via flask
wtforms==3.1.2
    # via flask-wtf
```

```python
# flask view

@main_bp.route("/sort_pdf", methods=["POST"])
@login_required
def sort_pdf():
    pdf_file = request.files.get("pdf_file")
    pdf_type = request.form.get("pdf_type", type=int)
    if pdf_file:
        try:
            sorted_file = sort_pdf_by_postcode(pdf_file, pdf_type)
            return send_file(sorted_file, download_name="sorted_pdf.pdf", as_attachment=True)
        except PdfOperationX as e:
            flash(f"An error occurred: {e}", category="Error")
            return redirect(url_for("main_bp.index"))

    flash("No PDF file provided", category="Error")
    return redirect(url_for("main_bp.index"))
```

```python
# function where error happens

import io
import logging
from typing import BinaryIO

import pymupdf

logger = logging.getLogger(__name__)


class PdfOperationX(Exception):
    pass


def sort_pdf_by_postcode(pdf_file: BinaryIO, pdf_type: int) -> io.BytesIO:
    if pdf_type not in [1, 2, 3]:
        raise PdfOperationX("Invalid PDF type.")

    with pymupdf.open(pdf_file) as pdf:
        rect = pdf[0].first_annot.rect  # ReferenceError('weakly-referenced object no longer exists')

    ...
```

```python-traceback
# flask error traceback

127.0.0.1 - - [16/Sep/2024 19:06:10] "POST /sort_pdf HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/app/auth/views.py", line 16, in decorated_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/app/routes.py", line 22, in sort_pdf
    sorted_file = sort_pdf_by_postcode(pdf_file, pdf_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/app/domain.py", line 21, in sort_pdf_by_postcode
    rect = pdf[0].first_annot.rect
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pymupdf/__init__.py", line 1025, in rect
    val *= p.derotation_matrix
           ^^^^^^^^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
```

```python-traceback
# pytest traceback

============================================================================================= test session starts =============================================================================================
platform linux -- Python 3.11.8, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/burakcank/Documents/postwork/app
configfile: pyproject.toml
collected 2 items                                                                                                                                                                                             

tests/test_domain.py Fatal Python error: Segmentation fault

Current thread 0x00007c4058feab80 (most recent call first):
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pymupdf/mupdf.py", line 48581 in pdf_annot_type
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pymupdf/__init__.py", line 1340 in type
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pymupdf/__init__.py", line 367 in __repr__
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_io/saferepr.py", line 73 in repr_instance
  File "/home/burakcank/.pyenv/versions/3.11.8/lib/python3.11/reprlib.py", line 63 in repr1
  File "/home/burakcank/.pyenv/versions/3.11.8/lib/python3.11/reprlib.py", line 53 in repr
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_io/saferepr.py", line 62 in repr
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_io/saferepr.py", line 111 in saferepr
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 838 in repr_args
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 937 in repr_traceback_entry
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 992 in <listcomp>
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 991 in repr_traceback
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 1058 in repr_excinfo
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/_code/code.py", line 690 in getrepr
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/nodes.py", line 456 in _repr_failure_py
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/python.py", line 1669 in repr_failure
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/reports.py", line 376 in from_item_and_call
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/runner.py", line 368 in pytest_runtest_makereport
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/runner.py", line 244 in call_and_report
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/main.py", line 362 in pytest_runtestloop
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/main.py", line 337 in _main
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/main.py", line 283 in wrap_session
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/home/burakcank/Documents/postwork/app/venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/home/burakcank/Documents/postwork/app/venv/bin/pytest", line 8 in <module>

Extension modules: markupsafe._speedups, pymupdf._extra, pymupdf._mupdf (total: 3)
fish: Job 1, 'pytest' terminated by signal SIGSEGV (Address boundary error)
```

### PyMuPDF version

1.24.10

### Operating system

Linux

### Python version

3.11

**Comment by JorjMcKie** [comment]
This is a bug in your script. For some background read [this](https://pymupdf.readthedocs.io/en/latest/app3.html#ensuring-consistency-of-important-objects-in-pymupdf) section of the documentation.
There is a hierarchical relationship between pages and their annotations controlled by the weakref module. If a page is de-referenced, all its existing annotation objects are invalidated.
In a few words, this means that `doc[0].first_annot` creates an annotation that is "born as an orphan", because the page is created via `doc[0]` and immediately deleted again if not assigned to `page` to prevent its subsequent deletion.
SO, instead of doing this:
```python
rect = pdf[0].first_annot.rect
```
Do this:
```python
page = pdf[0]
rect = page.first_annot.rect
```

**Comment by burakcank** [comment]
@JorjMcKie thank you for quick response.
