### ISSUE TITLE
Error inserting page, resulting in uncaught exception

### ISSUE THREAD

**Issue by cmyers009** [pymupdf/PyMuPDF#3927]
### Description of the bug

```
Traceback (most recent call last):\n' +
      '  File "D:\\test.py", line 594, in test_function\n' +
      '    doc.insert_pdf(input_pdf, from_page=page_num, to_page=page_num)\n' +
      '  File "C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymupdf\\__init__.py", line 4504, in insert_pdf\n' +
      '    extra_FzDocument_insert_pdf(\n' +
      '  File "C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymupdf\\extra.py", line 72, in FzDocument_insert_pdf\n' +
      '    return _extra.FzDocument_insert_pdf(doc, src, from_page, to_page, start_at, rotate, links, annots, show_progress, final, graft_map)\n' +
      '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
      'RuntimeError: code=2: realloc (69590960 bytes) failed\n'


### How to reproduce the bug

Only happens on rare occasions, but is reproducible for specific pdfs.

When opening a pdf and inserting the page into a new pdf, there is rarely a runtime realloc error.

Unable to provide specific pdf example, but wanted to report the issue in case it can be tracked down without the pdf.

### PyMuPDF version

1.24.7

### Operating system

Windows

### Python version

3.11

**Comment by JorjMcKie** [comment]
We cannot accept this as an issue report.
We always need a reproducing situation with file and the newest PyMuPDF version.

**Comment by JorjMcKie** [comment]
I am going to close this for now.
Please feel free to reopen it with a reproducible data, or submit a new issue.
