### ISSUE TITLE
Termux build and install from source. 

### ISSUE THREAD

**Issue by sunshinewithmoonlight** [pymupdf/PyMuPDF#544]
Im trying to build it on my Android phone in the Termux  environment. Here is what I get:
```
$ ls   
PKG-INFO  fitz  setup.py
$ tree
.
├── PKG-INFO
├── fitz
│   ├── __init__.py
│   ├── __main__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   └── fitz.cpython-38.pyc
│   ├── fitz
│   │   ├── archive.h
│   │   ├── band-writer.h
│   │   ├── bidi.h
│   │   ├── bitmap.h
│   │   ├── buffer.h
│   │   ├── color.h
│   │   ├── compress.h
│   │   ├── compressed-buffer.h
│   │   ├── config.h
│   │   ├── context.h
│   │   ├── crypt.h
│   │   ├── device.h
│   │   ├── display-list.h
│   │   ├── document.h
│   │   ├── filter.h
│   │   ├── font.h
│   │   ├── geometry.h
│   │   ├── getopt.h
│   │   ├── glyph-cache.h
│   │   ├── glyph.h
│   │   ├── hash.h
│   │   ├── image.h
│   │   ├── link.h
│   │   ├── log.h
│   │   ├── outline.h
│   │   ├── output-svg.h
│   │   ├── output.h
│   │   ├── path.h
│   │   ├── pixmap.h
│   │   ├── pool.h
│   │   ├── separation.h
│   │   ├── shade.h
│   │   ├── store.h
│   │   ├── stream.h
│   │   ├── string-util.h
│   │   ├── structured-text.h
│   │   ├── system.h
│   │   ├── text.h
│   │   ├── track-usage.h
│   │   ├── transition.h
│   │   ├── tree.h
│   │   ├── util.h
│   │   ├── version.h
│   │   ├── write-pixmap.h
│   │   ├── writer.h
│   │   └── xml.h
│   ├── fitz.h
│   ├── fitz.py
│   ├── fitz_wrap.c
│   ├── memento.h
│   ├── pdf
│   │   ├── annot.h
│   │   ├── clean.h
│   │   ├── cmap.h
│   │   ├── crypt.h
│   │   ├── document.h
│   │   ├── event.h
│   │   ├── font.h
│   │   ├── form.h
│   │   ├── interpret.h
│   │   ├── javascript.h
│   │   ├── name-table.h
│   │   ├── object.h
│   │   ├── output-pdf.h
│   │   ├── page.h
│   │   ├── parse.h
│   │   ├── resource.h
│   │   └── xref.h
│   ├── pdf.h
│   ├── ucdn.h
│   └── utils.py
└── setup.py
```
When I execute "python setup.py install" and try "import fitz" in python, the error occurs:
```
Python 3.8.3 (default, Jun 27 2020, 11:28:29) 
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: dlopen failed: "/data/data/com.termux/files/usr/lib/python3.8/site-packages/fitz/_fitz.cpython-38.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
```
What can I do during the build process?

**Comment by JorjMcKie** [comment]
I have zero experience with this environment, so probably cannot help you.
But, as for all platforms, you must follow a 2-step approach:
1. Build MuPDF **_for the desired operating system._** Use MuPDF-provided build instructions for the OS to do this.
2. Get PyMuPDF source and **_update setup.py_** with the folder names of the above MuPDF build.

Then build PyMuPDF - again for the **_specific OS_** environment. No idea what must be done to Python so it supports Android ...
For sure you need the development Python version for that environment ...
