### ISSUE TITLE
Error when adding rect annot to PDF page

### ISSUE THREAD

**Issue by chanhlt12** [pymupdf/PyMuPDF#767]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Error when adding rect annot: 
```shell
mupdf: rect must be finite and not empty
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    annot = page.addRectAnnot(rect)
  File "C:\Python37\lib\site-packages\fitz\fitz.py", line 5224, in addRectAnnot
    annot = self._add_square_or_circle(rect, PDF_ANNOT_SQUARE)
  File "C:\Python37\lib\site-packages\fitz\fitz.py", line 5147, in _add_square_or_circle
    return _fitz.Page__add_square_or_circle(self, rect, annot_type)
RuntimeError: rect must be finite and not empty
```

## To Reproduce (mandatory)
Here is my code:
```python
import fitz

rect = fitz.Rect(
    86.49209822394218,
    188.71276585069234,
    147.07247049569972,
    187.29678781584607,
)

doc = fitz.open()
page = doc.newPage()
annot = page.addRectAnnot(rect)
annot.update()
```

## Your configuration (mandatory)
 - Windows 10 Home
 - Python 3.7.8 64bit
 - PyMuPDF 1.18.4

**Comment by chanhlt12** [comment]
I am sorry this was my mistake.
The y2 is smaller than y1. this is not a valid value.
