### ISSUE TITLE
Installation error with pip [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2

### ISSUE THREAD

**Issue by dynamoh** [pymupdf/PyMuPDF#955]
We are using python 2.7.18
```
pip install PyMuPDF
Collecting PyMuPDF
  Using cached https://files.pythonhosted.org/packages/6a/c2/1891e193f30a61eb1442eda59ff5aa0b9297ab5fd2bf932c729a12179a87/PyMuPDF-1.18.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c64nKO/PyMuPDF/setup.py", line 117, in <module>
        l = l.decode()
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c64nKO/PyMuPDF/
```
can anyone help ??

**Comment by JorjMcKie** [comment]
The latest PyMuPDF version wih support for Py2.7 was 1.18.4.

**Comment by JorjMcKie** [comment]
Some of the very last Py2.7 wheels have even not been uploaded to PyPI.
Please look here for a potential match: https://github.com/pymupdf/PyMuPDF-Optional-Material/tree/master/wheels-upto-Py3.5
